### ISSUE TITLE
Firefox port

### ISSUE THREAD

**Issue by lumiome** [0xa/chromium-ipfuck#4]
Please make one.

**Comment by 0xa** [comment]
it's a chrome port of https://addons.mozilla.org/fr/firefox/addon/ipflood/

**Comment by Murplugg** [comment]
That legacy Firefox extension is unavailable now.
Is it possible to re-implement from the Chrome extension?

**Comment by 0xa** [comment]
It is possible but i have very little interest in doing so. Feel free to.

**Comment by ariasuni** [comment]
Someone could fork this repository, include  [webextension-polyfill](https://github.com/mozilla/webextension-polyfill) and convert calls to `chrome` with callbacks to standards `browser` with Promise, so that the extension is compatible with both Firefox and Chrome.
